version: '3'

services:
  redis:
      image: 'redis:alpine'
      ports:
        - '6379:6379'
      restart: always
      expose:
        - '6379'
  wordpress:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html/wp-content/plugins/Plugin-Custom-Request
    environment:
      WORDPRESS_DB_HOST: mysql
      WORDPRESS_DB_USER: your_database_user
      WORDPRESS_DB_PASSWORD: your_database_password
      WORDPRESS_DB_NAME: your_database_name
      WORDPRESS_DEBUG: 'true'
  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: your_root_password
      MYSQL_DATABASE: your_database_name
      MYSQL_USER: your_database_user
      MYSQL_PASSWORD: your_database_password
    ports:
      - "3307:3306"