version: '3'

services:
  wordpress:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: container_custom_wp
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html/wp-content/plugins/Plugin-Custom-Request
    environment:
      WORDPRESS_DB_HOST: mysql
      WORDPRESS_DB_USER: your_database_user
      WORDPRESS_DB_PASSWORD: your_database_password
      WORDPRESS_DB_NAME: your_database_name
      WORDPRESS_DEBUG: 'true'
      WORDPRESS_CONFIG_EXTRA: |
        define( 'WP_REDIS_HOST', 'redis' );
        define( 'WP_REDIS_PORT', 6379 );
  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: your_root_password
      MYSQL_DATABASE: your_database_name
      MYSQL_USER: your_database_user
      MYSQL_PASSWORD: your_database_password